### ISSUE TITLE
Extend ObjectDetector to read local images through OpenCV

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/dl-objectdetector#29]
With no dependence on ICE or ROS communication layer

**Comment by naxvm** [comment]
Sure @jmplaza 

The intention is to handle a stream (_local video_) or a _single image/batch of images_?

**Comment by jmplaza** [comment]
local video o local camera

**Comment by naxvm** [comment]
That can already done streaming from <code>camserver</code> (old <code>cameraserver</code>). Though, that would involve an ICE/ROS (<code>comm</code>) driver. So, I understand the purpose is to read video/camera data directly through OpenCV, right? That would remove the dependency on JdeRobot for this component. Is that correct?

**Comment by naxvm** [comment]
ACK, working on it!

**Comment by naxvm** [comment]
Finished the integration.

All yours @rkachach :smiley:
