### ISSUE TITLE
Remove dependencies on ICE (config) when using local camera

### ISSUE THREAD

**Issue by rkachach** [JdeRobot/dl-objectdetector#31]
The config module and comm (which I think is part of ICE) are being used/imported when the user is using local camera. As consequence this forces the user to have ICE installed even when using a local video source.

**Comment by naxvm** [comment]
All fine. Thanks @rkachach!!

**Comment by naxvm** [comment]
ROS/ICE usage broken from this change (cfg file uncompliant with comm interface).

**Comment by alexandre2r** [comment]
Hi, I am using the comm interface in my project and it seems broken as @naxvm says. Is it any stable version available? I hardcoded some things in the source code of comm, hoping it will work but I did not test it properly yet... and it is not the best way to use it obviously.
